from .educacion_serializer.ocupacionSerializer import ocupacionRegistroSerializer, ocupacionSerializer
from .educacion_serializer.religionSerializer import religionRegistroSerializer, religionSerializer
from .educacion_serializer.gradosSerializer import gradosRegistroSerializer, gradosSerializer
from .educacion_serializer.generoSerializer import generoRegistroSerializer, generoSerializer
from .educacion_serializer.departamentoSerializer import departamentoRegistroSerializer, departamentoSerializer
from .educacion_serializer.centroSerializer import centroRegistroSerializer, centroSerializer
from .educacion_serializer.idiomaSerializer import idiomaRegistroSerializer, idiomaSerializer
from .educacion_serializer.convivienteSerializer import ConvivienteRegistroSerializer, ConvivienteSerializer
from .educacion_serializer.parentescoSerializer import ParentescoRegistroSerializer, ParentescoSerializer
from .educacion_serializer.servicio_aguaSerializer import Servicio_aguaRegistroSerializer, Servicio_aguaSerializer
from .educacion_serializer.tipo_muroSerializer import Tipo_muroRegistroSerializer, Tipo_muroSerializer
from .educacion_serializer.tipo_techoSerializer import Tipo_techoRegistroSerializer, Tipo_techoSerializer

