from .educacion_serializer.ocupacionSerializer import ocupacionRegistroSerializer, ocupacionSerializer
from .educacion_serializer.religionSerializer import religionRegistroSerializer, religionSerializer
from .educacion_serializer.gradosSerializer import gradosRegistroSerializer, gradosSerializer
from .educacion_serializer.generoSerializer import generoRegistroSerializer, generoSerializer
from .educacion_serializer.departamentoSerializer import departamentoRegistroSerializer, departamentoSerializer
from .educacion_serializer.centroSerializer import centroRegistroSerializer, centroSerializer
from .educacion_serializer.idiomaSerializer import idiomaRegistroSerializer, idiomaSerializer
