from .educacionForms.departamentoForm import  DepartamentoForm
from .educacionForms.municipioForm import MunicipioForm
from .educacionForms.parentescoForm import ParentescoForm
from .educacionForms.seccionForm import SeccionForm
from .educacionForms.psicoForm import PsicoForm
from .educacionForms.categoriaFormp import CategoriaForm
from .educacionForms.tpisoForm import TpisoForm
from .educacionForms.ocupaForm import OcupaForm
from .educacionForms.padForm import PadeForm
from .educacionForms.alPadeForm import APadeForm
from .educacionForms.centEduForm import CentEduForm
