from .educacionForms.departamentoForm import  DepartamentoForm
from .educacionForms.municipioForm import MunicipioForm
from .educacionForms.parentescoForm import ParentescoForm
from .educacionForms.seccionForm import SeccionForm
from .educacionForms.psicoForm import PsicoForm
from .educacionForms.categoriaFormp import CategoriaForm
from .educacionForms.tpisoForm import TpisoForm
from .educacionForms.ocupaForm import OcupaForm
from .educacionForms.padForm import PadeForm
from .educacionForms.alPadeForm import APadeForm
from .educacionForms.centEduForm import CentEduForm
from .educacionForms.cicloForm import CicloForm
from .educacionForms.cursoForm import CursoForm
from .educacionForms.generoForm import GeneroForm
from .educacionForms.gradosForm import GradosForm
from .educacionForms.idiomaForm import IdiomaForm
from .educacionForms.personalForms import PersonalForm
from .educacionForms.religionForm import ReligionForm
from .educacionForms.tareaForm import TareaForm
from .educacionForms.gradoForm import GradoForm
from .educacionForms.religionalumForm import ReligionAlumnoForm
from .educacionForms.techoForm import TechoForm
from .educacionForms.paredForm import ParedForm
from .educacionForms.etniaForm import EtniaForm
from .educacionForms.serviaguaForm import ServiaguaForm
from .educacionForms.convivienteForm import ConvivienteForm
from .educacionForms.tutorForm import TutorForm
from .educacionForms.alumnoForm import AlumnoForm
from .educacionForms.centroPerForm import CentPerForm
from .educacionForms.estantForm import EstAntForm
from .educacionForms.cgForm import CGForm
from .educacionForms.cgcForm import CGCForm
from .educacionForms.insForm import InsForm
from .educacionForms.viviendaForm import VivForm
#Municipalizacion
from .muniForms.areaForm import AreaForm
from .muniForms.cargrupForm import CarGForm
from .muniForms.idiomaperForm import IdPerForm
from .muniForms.personaForm import PersonaForm
from .muniForms.beneficiadoForm import BenForm
from .muniForms.maestroForm import MaestroForm
from .muniForms.profecionForm import ProfesionForm
from .muniForms.discapacidadForm import DiscForm
from .muniForms.cargoForm import CargoForm
from .muniForms.comisionForm import ComisionForm
from .muniForms.ausbenefiForm import AusenBeneficiadoForm
from .muniForms.establecimientoForm import EstablecimientoForm
from .muniForms.lidercomuniForm import LiderComuniMuniForm
from .muniForms.mediocomuForm import MedioComuniForm
from .muniForms.partidopoliticForm import PartidoPoliticForm
from .muniForms.tutormuniForm import TutorMuniForm
