# Generated by Django 3.2.7 on 2021-09-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ocupacion', models.CharField(max_length=50)),
                ('descripcion_ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_ocupacion', models.BooleanField(default=True)),
            ],
        ),
    ]
