# Generated by Django 3.2.7 on 2021-10-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectosSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractura', models.BooleanField(default=True)),
                ('descripcion_fractura', models.CharField(max_length=100)),
                ('operacion', models.BooleanField(default=True)),
                ('descripcion_operacion', models.CharField(max_length=50)),
                ('padecimiento', models.BooleanField(default=True)),
                ('descripcion_enfermedad', models.CharField(max_length=100)),
                ('recibe_tratamiento', models.BooleanField(default=True)),
                ('descripcion_tratamiento', models.CharField(max_length=100)),
                ('nombre_medicamento', models.CharField(max_length=50)),
                ('limitacion_fisica', models.BooleanField(default=True)),
                ('descripcion_limitacion', models.CharField(max_length=100)),
                ('estado_aspectosalud', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caract_laborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_trabajado', models.BooleanField(default=False)),
                ('razon_t', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('t_realizados', models.CharField(blank=True, max_length=100, null=True)),
                ('trabaja_actualmente', models.BooleanField(default=False)),
                ('empleador_p', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('fam_extranjero', models.BooleanField(default=False)),
                ('op_extranjero', models.BooleanField(default=False)),
                ('op_empleos', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
                ('propio', models.BooleanField(default=False)),
                ('s_americano', models.BooleanField(default=False)),
                ('estado_claborales', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado_actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradoact', models.CharField(max_length=150)),
                ('estado_gradoact', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pariente', models.CharField(max_length=100)),
                ('cantidad_mensual', models.FloatField(blank=True, null=True)),
                ('procedencia_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_infoeco', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEducacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=30)),
                ('direccion_establecimiento', models.CharField(max_length=50)),
                ('nombre_maestro', models.CharField(max_length=50)),
                ('tel_maestro', models.CharField(max_length=8)),
                ('nombre_grupo', models.CharField(max_length=30)),
                ('descripcion_grupo', models.CharField(max_length=50)),
                ('recibido_formacion', models.CharField(max_length=100)),
                ('conocimiento_derechoshumanos', models.CharField(max_length=100)),
                ('conocimiento_leyes', models.BooleanField(default=True)),
                ('importancia_organizacion', models.CharField(max_length=100)),
                ('te_motiva_participar', models.CharField(max_length=100)),
                ('que_esperas_participar', models.CharField(max_length=100)),
                ('estado_info_educacion', models.BooleanField(default=100)),
                ('jornada_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='I_jornada', to='app.jornadaestudios')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=40)),
                ('descripcion_taller', models.CharField(max_length=200)),
                ('estado_taller', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresp', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('DPIP', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=100)),
                ('tel_casa', models.CharField(max_length=8)),
                ('tel_cel', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cantidad_convivientes', models.IntegerField()),
                ('conquien_vive', models.CharField(max_length=100)),
                ('fotografiaP', models.ImageField(blank=True, null=True, upload_to='ceipa')),
                ('razon', models.CharField(max_length=200)),
                ('ingreso_total', models.FloatField()),
                ('total_gastos', models.FloatField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, default=None, null=True)),
                ('estado_persona_basica', models.BooleanField(default='True')),
                ('aspectos_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_aspectos_salud', to='app.aspectossalud')),
                ('etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_etnia', to='app.etnia')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_genero', to='app.genero')),
                ('info_educacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_info_educacion', to='app.infoeducacion')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_municipio', to='app.municipio')),
                ('padres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PB_padres', to='app.padressociop')),
            ],
        ),
        migrations.CreateModel(
            name='ElectVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electro_viv', to='app.electrodomesticos')),
            ],
        ),
    ]
