# Generated by Django 3.2.7 on 2021-10-24 17:37

from django.db import migrations

def createRol(apps, schema_editor):
    try:
        Rol = apps.get_model('app','Rol')
        Rol.objects.create(nombre_rol='Coordinador de educación')
        Rol.objects.create(nombre_rol='Asistente de educación')
        Rol.objects.create(nombre_rol='Director general')
        Rol.objects.create(nombre_rol='Asistente director general')
        Rol.objects.create(nombre_rol='Director de centro')
        Rol.objects.create(nombre_rol='Maestro')
        Rol.objects.create(nombre_rol='Coordinador de municipalización')
        Rol.objects.create(nombre_rol='Asistente de municipalización')
        Rol.objects.create(nombre_rol='Equipo técnico de municipalización')
        Rol.objects.create(nombre_rol='Coordinador socioproductivo')
        Rol.objects.create(nombre_rol='Asistente socioproductivo')
        Rol.objects.create(nombre_rol='Equipo técnico socioproductivo')
    except Exception as e:
        print('error al crear modelo', e)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createRol)
    ]
