# Generated by Django 3.2.7 on 2021-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomesticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_electro', models.CharField(max_length=30)),
                ('estado_electro', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=30)),
                ('cantidad_servicio', models.CharField(max_length=100)),
                ('estado_gastofamiliar', models.BooleanField(default=True)),
            ],
        ),
    ]
