# Generated by Django 3.2.7 on 2021-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='Pargrupo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='Renas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='vacuna_covid',
            field=models.BooleanField(default=True),
        ),
    ]
