# Generated by Django 3.2.7 on 2021-10-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fotografia',
            new_name='fotografia_persona',
        ),
        migrations.RenameField(
            model_name='tutormuni',
            old_name='fotografia',
            new_name='fotografia_tutor',
        ),
    ]
