# Generated by Django 3.2.7 on 2021-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
