# Generated by Django 3.2.7 on 2021-10-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aspectossalud_caract_laborales_electvivienda_grado_actual_infoeconomica_infoeducacion_personabasica_'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViviendaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitantes', models.IntegerField()),
                ('otra_Viv', models.BooleanField(default='False')),
                ('desc_Otra_Viv', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=8)),
                ('agua_potable', models.BooleanField(default='False')),
                ('energia_elect', models.BooleanField(default='False')),
                ('dreaje', models.BooleanField(default='False')),
                ('nivel_Eco_Alto', models.BooleanField(default='False')),
                ('nivel_Eco_medio', models.BooleanField(default='False')),
                ('nivel_Eco_bajo', models.BooleanField(default='False')),
                ('pobre', models.BooleanField(default='False')),
                ('no_pobre', models.BooleanField(default='False')),
                ('Extemadamente_pobre', models.BooleanField(default='False')),
                ('estado_vivsocio', models.BooleanField(default='True')),
                ('tipomuro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VS_Tipo_muro', to='app.tipo_muro')),
                ('tipopiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VS_Tipo_piso', to='app.tipo_piso')),
                ('tipotecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_techo', to='app.tipo_techo')),
                ('tipovivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VS_Categoria', to='app.categoria')),
            ],
        ),
    ]
