# Generated by Django 3.2.7 on 2021-11-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211031_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiado',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_benef',
        ),
    ]
