# Generated by Django 3.2.7 on 2021-10-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_viviendasocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viviendasocio',
            name='Extemadamente_pobre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='agua_potable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='dreaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='energia_elect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='estado_vivsocio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='nivel_Eco_Alto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='nivel_Eco_bajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='nivel_Eco_medio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='no_pobre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='otra_Viv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viviendasocio',
            name='pobre',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_encar', models.IntegerField()),
                ('apellidos_encar', models.IntegerField()),
                ('fecha_nacimientoE', models.DateField()),
                ('TelefonoE', models.CharField(max_length=8)),
                ('estado_Encargado', models.BooleanField(default=True)),
                ('octutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='E_OcupacionTutor', to='app.ocupaciontutor')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='E_Parentesco', to='app.parentesco')),
            ],
        ),
    ]
