# Generated by Django 3.2.7 on 2021-10-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211025_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='apellidos_encar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='nombres_encar',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_emp', models.CharField(max_length=255)),
                ('Monto_Capital', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('estado_Emprendimiento', models.BooleanField(default=True)),
                ('Tipoemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Em_tipoemp', to='app.tipoemp')),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Em_muni', to='app.municipio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Em_Persona', to='app.personabasica')),
            ],
        ),
    ]
