from .educacionViewset.departamentoViewset import DepartamentoView, DepartamentoNew, DepartamentoEdit, DepartamentoDel
from .educacionViewset.municipioViewset import MunicipioView, MunicipioNew, MunicipioEdit, MunicipioDel
from .educacionViewset.parentescoViewset import ParentescoView, ParentescoNew, ParentescoEdit, ParentescoDel
from .educacionViewset.seccionviewset import SeccionView, SeccionNew, SeccionEdit, SeccionDel
from .educacionViewset.psicoViewset import PicoView, PsicoNew, PsicoEdit, PsicoDel
from .educacionViewset.catViewset import CatView, CatNew, CatEdit, CatDel
from .educacionViewset.tpisoViewset import TpisoView, TpisoNew, TpisoEdit, TpisoDel
from .educacionViewset.ocupViewset import OcupView, OcupNew, OcupEdit, OcupDel
from .educacionViewset.padViewset import PadView, PadNew, PadEdit, PadDel
from .educacionViewset.AlumPadViewset import APadView, APadNew, APadEdit, APadDel
from .educacionViewset.CenEduViewset import CenEdView, CenEdNew, CenEdEdit, CenEdDel
from .educacionViewset.homeViewset import Home
from .educacionViewset.cicloViewset import CicloView, CicloNew, CicloEdit, CicloDel
from .educacionViewset.cursoViewset import CursoView, CursoNew, CursoEdit, CursoDel
from .educacionViewset.generoViewset import GeneroView, GeneroNew, GeneroEdit, GeneroDel
from .educacionViewset.gradosViewset import GradosView, GradosNew, GradosEdit, GradosDel
from .educacionViewset.idiomaViewset import IdiomaView, IdiomaNew, IdiomaEdit, IdiomaDel
from .educacionViewset.personalViewset import PersonalView, PersonalNew, PersonalEdit, PersonalDel
from .educacionViewset.religionViewset import ReligionView, ReligionNew, ReligionEdit, ReligionDel
from .educacionViewset.tareaViewset import TareaView, TareaNew, TareaEdit, TareaDel
from .educacionViewset.gradoViewset import GradoView, GradoNew, GradoEdit, GradoDel
from .educacionViewset.religionalumViewset import Religion_alumnoView, Religion_alumnoNew, Religion_alumnoEdit, Religion_alumnoDel
from .educacionViewset.techoViewset import TechoView, TechoNew, TechoEdit, TechoDel
from .educacionViewset.paredViewset import ParedView, ParedNew, ParedEdit, ParedDel
from .educacionViewset.etniaViewset import EtniaView, EtniaNew, EtniaEdit, EtniaDel
from .educacionViewset.serviaguaViewset import ServiaguaView, ServiaguaNew, ServiaguaEdit, ServiaguaDel
from .educacionViewset.convivienteViewset import ConvivienteView, ConvivienteNew, ConvivienteEdit, ConvivienteDel
from .educacionViewset.tutorViewset import TutorView, TutorNew, TutorEdit, TutorDel
from .educacionViewset.alumnoViewset import AlumnoView, AlumnoNew, AlumnoEdit, AlumnoDel
from .educacionViewset.centperViewset import CentPerView, CentPerNew, CentPerEdit, CentPerDel
from .educacionViewset.estantViewset import EstAntView, EstAntNew, EstAntEdit, EstAntDel
from .educacionViewset.cgViewset import CGView, CGNew, CGEdit, CGDel
from .educacionViewset.cgcViewset import CGCView, CGCNew, CGCEdit, CGCDel
from .educacionViewset.insViewset import InsView, InsNew, InsEdit, InsDel
from .educacionViewset.viviendaViewset import VivView, VivNew, VivEdit, VivDel
from .educacionViewset.educacionViewset import HomeEducacion
#Municipalizacion
from .MunicViewset.municipalizacionViewset import HomeMunicipalizacion
from .MunicViewset.areaViewset import AreaView, AreaNew, AreaEdit, AreaDel
from .MunicViewset.curgradViewset import CarGView, CarGNew, CarGEdit, CarGDel
from .MunicViewset.idperViewset import IdPerView, IdPerNew, IdPerEdit, IdPerDel
from .MunicViewset.personaViewset import PerView, PerNew, PerEdit, PerDel
from .MunicViewset.benefViewset import BenView, BenNew, BenEdit, BenDel
from .MunicViewset.maestroViewset import MaesView, MaesNew, MaesEdit, MaesDel
from .MunicViewset.ProfesionViewset import ProfView, ProfNew, ProfEdit, ProfDel
from .MunicViewset.discViewset import DiscView, DiscNew, DiscEdit, DiscDel
from .MunicViewset.cargoViewset import CarView, CarNew, CarEdit, CarDel
from .MunicViewset.comisionViewset import ComView, ComNew, ComEdit, ComDel
from .MunicViewset.ausbenefiViewset import AusenBeneficiadoView, AusenBeneficiadoNew, AusenBeneficiadoEdit, AusenBeneficiadoDel
from .MunicViewset.establecimientoViewset import EstablecimientoView, EstablecimientoNew, EstablecimientoEdit, EstablecimientoDel
from .MunicViewset.lidercomuniViewset import LiderComunitarioMuniView, LiderComunitarioNew, LiderComunitarioEdit, LiderComunitarioDel
from .MunicViewset.mediocomuViewset import MedioComuniView, MedioComuniNew, MedioComuniEdit, MedioComuniDel
from .MunicViewset.partidopoliticViewset import PartidoPoliticView, PartidoPoliticNew, PartidoPoliticEdit, PartidoPoliticDel
from .MunicViewset.tutormuniViewset import TutorMuniView, TutorMuniNew, TutorMuniEdit, TutorMuniDel