from .educacion_model.ocupacion import ocupacion
from .educacion_model.religion import religion
from .educacion_model.grados import grados
from .educacion_model.genero import genero
from .educacion_model.tarea import tarea
from .educacion_model.personalEducativo import personalEducativo
from .educacion_model.tarea_alumno import tarea_alumno
from .educacion_model.vivienda import vivienda
from .educacion_model.departamento import departamento
from .educacion_model.centro_educativo import centro_educativo
from .educacion_model.idioma import idioma
from .educacion_model.conviviente import Conviviente
from .educacion_model.parentesco import Parentesco
from .educacion_model.servicio_agua import Servicio_Agua
from .educacion_model.alumnoModelo import Alumno
from .educacion_model.tipo_muro import Tipo_muro
from .educacion_model.tipo_techo import Tipo_techo
from .educacion_model.psicologicoModelo import psicologico
from .educacion_model.seccionModelo import seccion
from .educacion_model.categoriaModel import Categoria
from .educacion_model.tipopisoModel import Tipo_piso
from .educacion_model.centropersonaModel import Centropersona
from .educacion_model.estudiosantModel import EstudiosAnt
from .educacion_model.municipioModel import municipio
from .educacion_model.religion_alumno import Religion_alumno
from .educacion_model.grado import Grado
from .educacion_model.ciclo import Ciclo
from .educacion_model.curso import Curso
from .educacion_model.ciclo_grado import Ciclo_grado
from .educacion_model.ciclo_grado_curso import Ciclo_grado_curso
from .educacion_model.tutor import Tutor
from .educacion_model.padecimientoModel import Padecimiento
from .educacion_model.alumnopadecimiento import Apadecimiento
from .educacion_model.inscipsionesModel  import Inscripcion
from .educacion_model.etnia import etnia
#Municipalizacion
from .municipalizacionModel.area import Area
from .municipalizacionModel.ausencia import Ausencia
from .municipalizacionModel.Gorganizado import GOrganizado
from .municipalizacionModel.institucion import Institucion
from .municipalizacionModel.programaC import ProgramaC
from .municipalizacionModel.tutor_muni import TutorMuni
from .municipalizacionModel.establecimiento import Establecimiento
from .municipalizacionModel.mediocomu import MedioComuni
from .municipalizacionModel.partidopolitic import PartidoPolitic
from .municipalizacionModel.lider_comunitario import LiderComunitario
from .municipalizacionModel.ausen_beneficiado import AusenBeneficiado
from .municipalizacionModel.beneficiado import Beneficiado
from .municipalizacionModel.cargo import Cargo
from .municipalizacionModel.CarGrup import CargoGrupo
from .municipalizacionModel.comision import Comision
from .municipalizacionModel.idioPer import IdiomaPersona
from .municipalizacionModel.maestro import Maestro
from .municipalizacionModel.padper import PadPer
from .municipalizacionModel.persona import Persona
from .municipalizacionModel.profesion import Profesion
from .municipalizacionModel.comisionNA import ComisionNA
from .municipalizacionModel.benefArea import BeneficiadoArea
from .municipalizacionModel.padresFamilia import PadresFamilia
from .municipalizacionModel.corporacionMuni import CorporacionMunicipal
from .municipalizacionModel.discapacidad import Discapacidad
from .municipalizacionModel.gradoAcademico import GradoAcademico
from .educacion_model.aspectosLaborales import AspectosLab

#SocioProductivo
from .socioproductivoModel.tipo_emprendimiento import TipoEmp
from .socioproductivoModel.gasto_familiar import GastoFamiliar
from .socioproductivoModel.electrodomesticos import Electrodomesticos
from .socioproductivoModel.jornada_estudio import JornadaEstudios
from .socioproductivoModel.padres_familia import PadresSociop
from .socioproductivoModel.grupo_na import GrupoNA
from .socioproductivoModel.ocupacionTutor import OcupacionTutor
from .socioproductivoModel.grado_actual import Grado_actual
from .socioproductivoModel.info_economica import InfoEconomica
from .socioproductivoModel.caract_laborales import Caract_laborales
from .socioproductivoModel.aspectos_salud import AspectosSalud
from .socioproductivoModel.elect_vivienda import ElectVivienda
from .socioproductivoModel.talleres import Taller
from .socioproductivoModel.info_educacion import InfoEducacion
from .socioproductivoModel.persona_basica import PersonaBasica
from .socioproductivoModel.ViviendaSocio import ViviendaSocio
from .socioproductivoModel.encargado import Encargado
from .socioproductivoModel.emprendimiento import Emprendimiento
from .socioproductivoModel.inscripcionp import Inscripcionp
