from .educacion_model.ocupacion import ocupacion
from .educacion_model.religion import religion
from .educacion_model.grados import grados
from .educacion_model.genero import genero
from .educacion_model.tarea import tarea
from .educacion_model.personalEducativo import personalEducativo
from .educacion_model.tarea_alumno import tarea_alumno
from .educacion_model.vivienda import vivienda
from .educacion_model.departamento import departamento
from .educacion_model.centro_educativo import centro_educativo
from .educacion_model.idioma import idioma
from .educacion_model.conviviente import Conviviente
from .educacion_model.parentesco import Parentesco
from .educacion_model.servicio_agua import Servicio_Agua
from .educacion_model.alumnoModelo import Alumno
from .educacion_model.tipo_muro import Tipo_muro
from .educacion_model.tipo_techo import Tipo_techo
from .educacion_model.psicologicoModel import psicologico
from .educacion_model.seccionModel import seccion
from .educacion_model.categoriaModel import Categoria
from .educacion_model.tipopisoModel import Tipo_piso
from .educacion_model.centropersonaModel import Centropersona
from .educacion_model.estudiosantModel import EstudiosAnt
from .educacion_model.municipioModel import municipio
from .educacion_model.religion_alumno import Religion_alumno
from .educacion_model.grado import Grado
from .educacion_model.ciclo import Ciclo
from .educacion_model.curso import Curso
from .educacion_model.ciclo_grado import Ciclo_grado
from .educacion_model.ciclo_grado_curso import Ciclo_grado_curso
from .educacion_model.tutor import Tutor
